"""Builds the PolyDrive documentation from one source of truth:

    docs/DOCUMENTATION.md              (readable on GitHub)
    docs/PolyDrive_Documentation.pdf   (printable copy)

Run from the project folder:   .venv\\Scripts\\python tools\\build_docs.py
Needs reportlab (only for building the docs, not for playing):   pip install reportlab
Edit the CONTENT list below, then run the script again.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# Block types: h1, h2, h3, p, bullets, numbered, code, table (header, rows), note
CONTENT = [
    ("title", "PolyDrive", "Low-poly racing game with Arduino joystick support"),

    ("h1", "1. Overview"),
    ("p", "PolyDrive (game_3d.py) is a single-player time-trial racing game built with the Ursina engine "
          "(Python 3D, built on Panda3D). You drive a low-poly car along a flat road that has long bends, "
          "an S-bend and two U-turns, pass three checkpoints, collect coins for speed boosts and cross the "
          "finish line as fast as you can. It can be played on the keyboard, with an Arduino joystick board "
          "connected over USB serial, or both at the same time."),
    ("bullets", [
        "Course: flat road, about 2,300 units long, 16 units wide, with barriers on both sides.",
        "Race: timer starts when the car first moves; three checkpoints, the third is the finish line.",
        "Coins: about 35 gold discs along the road, each gives a speed boost.",
        "Sound: engine, tyre squeal, barrier thump and scrape, checkpoint, coin and win jingles, and a looping music track. All generated by the game itself.",
        "Controls: keyboard and/or two Arduino joysticks (analog throttle, brake and steering).",
    ]),

    ("h1", "2. Requirements and installation"),
    ("table", ["Item", "Version / note"], [
        ["Operating system", "Windows 11 (developed and tested there); Ursina also runs on macOS and Linux"],
        ["Python", "3.11"],
        ["ursina", "7.0.0 (pinned - see Troubleshooting: colors changed between versions)"],
        ["pyserial", "3.5 (only needed for the Arduino joystick; the game runs without it)"],
        ["Graphics", "Any GPU able to run Panda3D / OpenGL"],
    ]),
    ("h3", "First-time setup"),
    ("code", "cd wireless-game-controller\n"
             "python -m venv .venv\n"
             ".venv\\Scripts\\activate\n"
             "pip install -r requirements_stage2.txt"),
    ("p", "requirements_stage2.txt contains pygame (used by the 2D game), ursina and pyserial."),

    ("h1", "3. Running the game"),
    ("code", ".venv\\Scripts\\python game_3d.py"),
    ("bullets", [
        "The first start generates the sound files into the sounds/ folder (a few seconds). Later starts reuse them.",
        "Startup builds roughly 2,000 objects, so the window can take several seconds to appear.",
        "With the Arduino connected, the top-right corner shows 'Joystick: connected on COMx'.",
        "Esc quits the game.",
    ]),

    ("h1", "4. Controls"),
    ("h2", "Keyboard"),
    ("table", ["Key", "Action"], [
        ["W / Up arrow", "Accelerate (the longer you hold, the harder it pushes)"],
        ["S / Down arrow", "Brake, then reverse"],
        ["A, D / Left, Right arrows", "Steer (eases in and re-centres smoothly)"],
        ["Space", "Drift (tighter turning)"],
        ["R or Enter", "Return to the last checkpoint (timer keeps running)"],
        ["T or Backspace", "Start over from the beginning (coins come back)"],
        ["M", "Mute / unmute the music"],
        ["Esc", "Quit"],
    ]),
    ("h2", "Arduino joystick"),
    ("p", "Your board sends two sticks. Both work the same way; whichever is pushed furthest wins."),
    ("table", ["Stick movement", "Action"], [
        ["Left / right", "Steer (analog: a small push turns a little)"],
        ["Up", "Accelerate (analog: how far you push = how hard)"],
        ["Down", "Brake / reverse (analog)"],
        ["Press the stick (either)", "Drift"],
    ]),
    ("note", "Leave both sticks untouched while the game starts. It measures their resting position "
             "for about half a second and treats that as the centre."),

    ("h1", "5. Game rules"),
    ("bullets", [
        "Timer: starts when the car first moves. It shows Current, your Record (best finish) and the Difference (red = slower, green = faster).",
        "Checkpoints: 3 in total, at one third, two thirds and the end of the course. The counter (bottom left) shows how many you have passed. R / Enter returns you to the last one.",
        "Finish: passing the third checkpoint stops the timer and shows the win screen. R / Enter or T / Backspace starts a new race.",
        "Barriers: the car is kept on the road. Rubbing a barrier slows the car and plays a scrape; a hard hit plays a thump.",
        "Coins: each coin gives an instant +5 speed, plus 2.5 seconds of boost (up to 6 seconds stacked). While boosting, the car gets extra acceleration and a top speed 35 percent higher. The HUD shows BOOST and the seconds left.",
        "Falling off the world returns you to the last checkpoint.",
        "HUD speed: full speed reads 196 km/h. The physics top speed is 60 units per second; the number shown is scaled (see TOP_SPEED_DISPLAY).",
    ]),

    ("h1", "6. Arduino joystick hardware"),
    ("h2", "How it connects"),
    ("p", "The board appears as a serial (COM) port. The game reads lines of text from it on a background thread "
          "and never blocks the game loop. If the board is unplugged the game keeps running on the keyboard and "
          "retries every 2 seconds."),
    ("h2", "Data format (verified on the project board)"),
    ("code", "745,444,1,506,514,1\r\n"
             "^ stick 1: x, y, button   ^ stick 2: x, y, button\n"
             "\n"
             "Baud rate : 115200\n"
             "Axes      : 0-1023, centre near 506-514\n"
             "Button    : 1 at rest, 0 when pressed (active low)"),
    ("p", "The parser accepts any text line containing numbers: the 1st, 2nd and 3rd numbers are stick 1 (x, y, button) "
          "and the 4th, 5th and 6th are stick 2. A board that sends only three numbers works as a single stick."),
    ("h2", "Calibration"),
    ("bullets", [
        "The first 30 lines received are averaged to find each stick's centre.",
        "JOY_RANGE (400) is how far the raw value moves from the centre at full push. The range widens automatically if a stick reads further.",
        "JOY_DEADZONE (0.12) ignores tiny movements around the centre.",
    ]),
    ("h2", "Finding out what a board sends"),
    ("code", ".venv\\Scripts\\python tools\\serial_check.py"),
    ("p", "The tool lists COM ports, then reads the chosen port at 9600, 115200, 57600, 38400 and 19200 baud. "
          "The baud rate that prints readable lines is the right one. Close the Arduino IDE Serial Monitor first: only "
          "one program can use a COM port at a time."),
    ("h2", "If you use a blank Arduino instead"),
    ("p", "arduino/joystick_controller/joystick_controller.ino is a ready sketch (VRx to A0, VRy to A1, SW to D2, "
          "5V and GND). It sends 'x,y,button' at 115200 baud, which the game understands as a single stick. "
          "Because the sketch sends 1 when the button is pressed, set JOY_BUTTON_ACTIVE_LOW = False when using it."),

    ("h1", "7. Configuration reference"),
    ("p", "All tuning values are constants near the top of each section in game_3d.py. Change them and restart the game."),
    ("h3", "Driving"),
    ("table", ["Constant", "Default", "Meaning"], [
        ["MAX_SPEED", "60", "Top speed in world units per second"],
        ["TOP_SPEED_DISPLAY", "196", "Number shown on the HUD at top speed"],
        ["REVERSE_SPEED", "-15", "Top reverse speed"],
        ["ACCEL / BRAKE_DECEL / FRICTION", "30 / 50 / 10", "Acceleration, braking and coasting slow-down"],
        ["PEDAL_PRESS / PEDAL_RELEASE", "1.4 / 3.0", "How fast a key-driven pedal fills / empties (per second)"],
        ["TURN_SPEED", "110", "Turn rate in degrees per second at full steering"],
        ["STEER_RESPONSE / STEER_RETURN", "4.0 / 6.0", "How quickly the wheel turns toward the key / re-centres"],
        ["HIGH_SPEED_STEER", "0.6", "Share of steering lock left at top speed"],
        ["BODY_LEAN", "6", "Visual body tilt in degrees"],
        ["BARRIER_SCRAPE", "2.5", "Speed lost per second while rubbing a barrier"],
    ]),
    ("h3", "Course, camera and coins"),
    ("table", ["Constant", "Default", "Meaning"], [
        ["ROAD_WIDTH", "16", "Road width"],
        ["COURSE", "list", "Sequence of ('S', length) straights and ('A', degrees, radius) arcs; + = right, - = left"],
        ["CAMERA_BACK / CAMERA_HEIGHT", "12 / 6.5", "Chase camera distance and height"],
        ["CAMERA_LOOK_AHEAD / camera.fov", "8 / 80", "Aim point ahead of the car; field of view"],
        ["COIN_SPACING", "30", "Samples between coins (1 sample = 2 units)"],
        ["BOOST_SECONDS / BOOST_MAX_SECONDS", "2.5 / 6", "Boost per coin and the stacking limit"],
        ["BOOST_TOP_FACTOR / BOOST_ACCEL", "1.35 / 30", "Top-speed multiplier and extra acceleration while boosting"],
        ["COIN_KICK / COIN_PICKUP_RADIUS", "5 / 2.6", "Instant speed gain and pickup distance"],
        ["MUSIC_VOLUME", "0.35", "Music loudness (0 to 1)"],
    ]),
    ("h3", "Joystick"),
    ("table", ["Constant", "Default", "Meaning"], [
        ["SERIAL_PORT", "None", "Fixed port such as 'COM3'; None = auto-detect"],
        ["SERIAL_BAUD", "115200", "Must match the Arduino program"],
        ["JOY_RANGE", "400", "Raw distance from centre at full push"],
        ["JOY_DEADZONE", "0.12", "Dead area around the centre"],
        ["JOY_INVERT_X / JOY_INVERT_Y", "False / True", "Flip an axis (Y True means stick up = accelerate)"],
        ["JOY_BUTTON_ACTIVE_LOW", "True", "True if the button reads 0 when pressed"],
    ]),

    ("h1", "8. How it works (architecture)"),
    ("h2", "Files"),
    ("table", ["Path", "Purpose"], [
        ["game_3d.py", "The whole game (one file, organised in labelled sections)"],
        ["game_2d.py", "Separate earlier 2D coin game (not covered here)"],
        ["tools/serial_check.py", "Shows what an Arduino sends, per baud rate"],
        ["tools/build_docs.py", "Regenerates this documentation (Markdown and PDF)"],
        ["arduino/joystick_controller/", "Sketch for a blank Arduino + joystick module"],
        ["sounds/", "Generated audio (git-ignored, recreated on first run)"],
        ["docs/", "This documentation"],
        ["requirements_stage2.txt", "Pinned dependencies"],
    ]),
    ("h2", "Sections of game_3d.py (in order)"),
    ("numbered", [
        "Imports and app: Ursina(development_mode=False), asset folder set to sounds/.",
        "Lighting and sky: directional sun, ambient light, unlit sky dome.",
        "Course: COURSE turns into 'samples', one point every 2 units along the road centre-line, each with (x, z, heading). Everything else is built from those samples.",
        "Ground, trees and mountains: a large ground slab; trees and mountains are placed only where distance_to_road() is large enough.",
        "Road tiles and barriers: solid 2-unit-thick slabs (long on straights, short on curves) with barriers and a dashed centre line.",
        "Start, checkpoint and finish gates.",
        "Coins: gold discs placed on the road, weaving left, centre and right.",
        "Car: built from cubes; physics constants and state variables.",
        "Sound: file generation, load_sound() helper with a silent fallback, and the render_music() track.",
        "Helper functions: approach(), get_ground_y(), find_track_index(), place_car(), reset_race(), return_to_checkpoint().",
        "HUD: dark-blue panels built on camera.ui.",
        "Camera settings and the Joystick class (background thread).",
        "input(key) and update(): the per-frame game loop.",
    ]),
    ("h2", "Per-frame loop (update)"),
    ("numbered", [
        "Read pedals: keyboard keys ramp the pedal up; joystick gives an analog value.",
        "Apply acceleration, braking, friction and the coin boost; enforce the speed limit.",
        "Steering: ease the wheel toward the input, turn the car by steer * TURN_SPEED * grip.",
        "Move the car forward, find the nearest road sample, and push the car back inside the barriers (with scrape and thump).",
        "Vertical physics: a downward ray finds the road or ground height; gravity applies if the car is airborne.",
        "Timer, checkpoints and finish detection (based on the nearest road sample index).",
        "Coins: spin, and collect when the car is within 2.6 units.",
        "Chase camera follows and looks ahead of the car (world up vector, so it never rolls).",
        "Sound: engine pitch and volume, skid and scrape volumes.",
        "HUD text is refreshed.",
    ]),
    ("h2", "Audio"),
    ("p", "No audio files are shipped. make_sounds() writes 16-bit mono WAV files into sounds/ the first time the game "
          "runs: engine loop (harmonics of 55 Hz), tyre squeal (noise plus tones), scrape, thump, checkpoint and win "
          "jingles, coin chime and an 8-bar music loop at 124 BPM (kick, snare, hi-hat, bass and arpeggio over Am - F - C - G, "
          "with a drum break in the last bar). Engine pitch follows speed. If sounds cannot be created or loaded, "
          "SilentSound stand-ins are used and the game runs without audio."),
    ("h2", "Joystick thread"),
    ("p", "Joystick._run() runs as a daemon thread: find the port, open it, read lines, parse numbers, calibrate, then "
          "write x, y and button into the joystick object. The game loop only reads joystick.x, joystick.y and "
          "joystick.button. On any serial error the values reset to zero and the thread retries."),

    ("h1", "9. Verification performed"),
    ("p", "The game was checked with scripted tests (no human driving) before this documentation was written:"),
    ("table", ["Check", "Result"], [
        ["Code compiles, static check (pyflakes)", "Clean (only Ursina star-import notices)"],
        ["Production start (dev mode off, no editor overlay)", "Confirmed development_mode is False"],
        ["Road solidity: ray cast at 78 points along the whole course", "All found the road at height 0.15"],
        ["Autopilot lap: full throttle, steering toward the road", "Finished, 3 of 3 checkpoints, 11 coins, max speed 81 (60 x 1.35 cap)"],
        ["Reset and return-to-checkpoint after a finish", "Worked"],
        ["Fake two-stick Arduino stream", "Second stick alone gave full steering and throttle; active-low button detected"],
        ["pyserial missing", "Game starts, status reads 'install pyserial to use it'"],
        ["Fresh clone: sounds/ deleted", "All 8 sound files regenerated and loaded"],
    ]),
    ("note", "Not verified by these tests: how the game looks and sounds, and behaviour with the real Arduino "
             "hardware. Do a manual play-through (checklist below) on the target machine."),
    ("h2", "Manual check before a release"),
    ("bullets", [
        "Game opens with the scene visible (not white) and the HUD panels drawn.",
        "Car accelerates, steers and brakes on the keyboard; engine pitch rises with speed.",
        "Tyre squeal on hard braking; thump and scrape against a barrier.",
        "Coins disappear when collected, BOOST timer appears, speed goes above 196.",
        "All 3 checkpoints count; R / Enter returns to the last; T / Backspace restarts and restores coins.",
        "Finish shows the win screen and Record / Difference update on the next lap.",
        "Joystick: status says connected; up = accelerate, right = steer right, button = drift, for both sticks.",
        "Music plays and M mutes it; Esc quits.",
    ]),

    ("h1", "10. Troubleshooting and debugging"),
    ("table", ["Symptom", "Cause and fix"], [
        ["Whole 3D view is white, HUD text visible",
         "Ursina 7 changed color.rgb() to take 0-1 values. Use color.rgb32() / rgba32() for 0-255 values. Keep ursina pinned to 7.0.0."],
        ["Game hangs at startup, no window",
         "Something in the object-building code loops forever or is very slow. Use python -X faulthandler and faulthandler.dump_traceback_later(30) to see where it is. (Past cause: a while loop that never incremented its counter.)"],
        ["Startup is slow",
         "Ursina scans the asset folder recursively. The game sets the asset folder to sounds/ so it never scans .venv. Do not move that line."],
        ["Car sinks into the road / hills",
         "raycast hit.point is local to the hit object. Use hit.world_point (already done in get_ground_y). Road colliders must be top-level entities, not children of a rotated parent."],
        ["Camera turns upside down or rolls",
         "Entity.look_at uses the camera's own up vector by default. The game passes up=Vec3(0, 1, 0)."],
        ["No sound",
         "Check the sounds/ folder has 8 .wav files (delete it to regenerate). Console prints '[sound] ... unavailable' if a clip fails. Press M in case it is muted."],
        ["Status: 'install pyserial to use it'", "pip install pyserial in the same .venv the game runs from."],
        ["Status: 'no Arduino found'",
         "Check the USB cable and drivers; run tools/serial_check.py; set SERIAL_PORT = 'COM3' (your port)."],
        ["Serial port opens but the joystick does nothing",
         "Wrong baud rate (run serial_check.py) or the Arduino IDE Serial Monitor is still open and holding the port."],
        ["Up brakes / right steers left", "Flip JOY_INVERT_Y / JOY_INVERT_X."],
        ["Car creeps or steers by itself", "A stick was held during startup or has drift: raise JOY_DEADZONE, restart with sticks released."],
        ["Cannot reach full throttle on the stick", "Lower JOY_RANGE (the raw value never travels as far as 512 on some sticks)."],
        ["Button drifts constantly or never", "Toggle JOY_BUTTON_ACTIVE_LOW."],
        ["Music too loud or quiet", "Change MUSIC_VOLUME; the engine volume is set in the Sound part of update()."],
    ]),
    ("h2", "Useful debug techniques"),
    ("bullets", [
        "Scripted driving: run the game file with app.run() removed, set ursina.time.dt = 1/60, hold keys through ursina.held_keys, and call update() in a loop, then inspect speed, track_index and checkpoints_passed. This is how the lap test above was done.",
        "Fake Arduino: replace sys.modules['serial'] with an object whose readline() returns test lines to exercise the joystick code without hardware.",
        "Raw serial data: tools/serial_check.py prints exactly what the board sends.",
    ]),

    ("h1", "11. Known limitations and ideas"),
    ("bullets", [
        "Single course; the course is data (COURSE list), so new layouts are easy to add. Avoid layouts where road parts come within about 30 units of each other.",
        "No opponents, ghost car or saved records: the Record resets when the game closes.",
        "The car does not collide with trees or mountains (they are scenery); the barriers keep it on the road.",
        "Joystick calibration assumes the sticks are at rest at startup.",
        "Only one serial device is used; the game picks the first likely Arduino / USB serial port.",
        "Ideas: save best time to a file, ghost replay, more courses, wireless controller support, gamepad support through pygame.",
    ]),

    ("h1", "12. Change log of this development session"),
    ("bullets", [
        "Fixed the white screen (Ursina 7 color API), then removed the shadow shader and fog.",
        "Rebuilt the course: from a stadium loop with a jump, to a straight road, to the current flat course with bends and U-turns.",
        "Analog pedals and smoothed steering; body lean; chase camera that looks ahead.",
        "PolyTrack-style HUD with checkpoints, Record / Current / Difference.",
        "Generated sound effects and music; coins with speed boost.",
        "Arduino joystick support over serial, verified against the real board's output (two sticks, 115200 baud).",
        "Production hardening: dev mode off, asset folder fix, silent audio fallback, respawn at checkpoint, pinned requirements, .gitignore cleaned (sounds/ ignored).",
    ]),
]


# ------------------------------------------------------------------ Markdown

def md_escape_cell(text):
    return text.replace("|", "\\|")


def to_markdown():
    out = []
    for block in CONTENT:
        kind = block[0]
        if kind == "title":
            out.append(f"# {block[1]}\n\n_{block[2]}_\n")
        elif kind == "h1":
            out.append(f"\n## {block[1]}\n")
        elif kind == "h2":
            out.append(f"\n### {block[1]}\n")
        elif kind == "h3":
            out.append(f"\n#### {block[1]}\n")
        elif kind == "p":
            out.append(block[1] + "\n")
        elif kind == "note":
            out.append("> **Note:** " + block[1] + "\n")
        elif kind == "bullets":
            out.append("\n".join(f"- {item}" for item in block[1]) + "\n")
        elif kind == "numbered":
            out.append("\n".join(f"{i}. {item}" for i, item in enumerate(block[1], 1)) + "\n")
        elif kind == "code":
            out.append("```\n" + block[1] + "\n```\n")
        elif kind == "table":
            header, rows = block[1], block[2]
            lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
            lines += ["| " + " | ".join(md_escape_cell(c) for c in row) + " |" for row in rows]
            out.append("\n".join(lines) + "\n")
    return "\n".join(out)


# ------------------------------------------------------------------ PDF

def to_pdf(path):
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        ListFlowable, ListItem, PageBreak, Paragraph, Preformatted, SimpleDocTemplate,
        Spacer, Table, TableStyle, KeepTogether,
    )

    navy = colors.HexColor("#1c2869")
    styles = getSampleStyleSheet()
    body = ParagraphStyle("body", parent=styles["BodyText"], fontName="Helvetica", fontSize=10, leading=14)
    cell = ParagraphStyle("cell", parent=body, fontSize=8.6, leading=11)
    cell_head = ParagraphStyle("cellh", parent=cell, fontName="Helvetica-Bold", textColor=colors.white)
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=16, textColor=navy,
                        spaceBefore=14, spaceAfter=6)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=12.5, textColor=navy,
                        spaceBefore=10, spaceAfter=4)
    h3 = ParagraphStyle("h3", parent=styles["Heading3"], fontName="Helvetica-Bold", fontSize=10.5, textColor=navy,
                        spaceBefore=8, spaceAfter=3)
    code_style = ParagraphStyle("code", fontName="Courier", fontSize=8.6, leading=11, backColor=colors.HexColor("#f0f2fa"),
                                borderPadding=6, leftIndent=6, rightIndent=6, spaceBefore=4, spaceAfter=8)
    note_style = ParagraphStyle("note", parent=body, backColor=colors.HexColor("#fff6d6"), borderPadding=6,
                                leftIndent=6, rightIndent=6, spaceBefore=4, spaceAfter=8)
    title_style = ParagraphStyle("title", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=30,
                                 textColor=navy, alignment=TA_CENTER, spaceBefore=90, spaceAfter=10)
    sub_style = ParagraphStyle("sub", parent=body, fontSize=13, alignment=TA_CENTER, textColor=colors.HexColor("#444444"))

    def esc(text):
        text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return re.sub(r"`([^`]+)`", r"<font face='Courier'>\1</font>", text)

    def on_page(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#666666"))
        canvas.drawString(18 * mm, 10 * mm, "PolyDrive documentation")
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    story = []
    for block in CONTENT:
        kind = block[0]
        if kind == "title":
            story += [Paragraph(esc(block[1]), title_style), Paragraph(esc(block[2]), sub_style),
                      Spacer(1, 20), Paragraph("Usage guide, configuration reference and debugging notes", sub_style),
                      PageBreak()]
        elif kind == "h1":
            story.append(Paragraph(esc(block[1]), h1))
        elif kind == "h2":
            story.append(Paragraph(esc(block[1]), h2))
        elif kind == "h3":
            story.append(Paragraph(esc(block[1]), h3))
        elif kind == "p":
            story.append(Paragraph(esc(block[1]), body))
            story.append(Spacer(1, 4))
        elif kind == "note":
            story.append(Paragraph("<b>Note:</b> " + esc(block[1]), note_style))
        elif kind in ("bullets", "numbered"):
            items = [ListItem(Paragraph(esc(t), body), leftIndent=14) for t in block[1]]
            if kind == "bullets":
                story.append(ListFlowable(items, bulletType="bullet", start="-", leftIndent=14))
            else:
                story.append(ListFlowable(items, bulletType="1", leftIndent=16))
            story.append(Spacer(1, 4))
        elif kind == "code":
            story.append(Preformatted(block[1], code_style))
        elif kind == "table":
            header, rows = block[1], block[2]
            width = A4[0] - 36 * mm
            n = len(header)
            weights = {2: [0.34, 0.66], 3: [0.3, 0.14, 0.56]}.get(n, [1 / n] * n)
            data = [[Paragraph(esc(h), cell_head) for h in header]]
            data += [[Paragraph(esc(c), cell) for c in row] for row in rows]
            table = Table(data, colWidths=[width * w for w in weights], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), navy),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eef1fb")]),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#b9c0dd")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story += [table, Spacer(1, 8)]

    doc = SimpleDocTemplate(str(path), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=18 * mm,
                            title="PolyDrive documentation", author="PolyDrive project")
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    (DOCS / "DOCUMENTATION.md").write_text(to_markdown(), encoding="utf-8", newline="\n")
    print("wrote", DOCS / "DOCUMENTATION.md")
    try:
        to_pdf(DOCS / "PolyDrive_Documentation.pdf")
        print("wrote", DOCS / "PolyDrive_Documentation.pdf")
    except ImportError:
        sys.exit("reportlab is not installed: pip install reportlab   (needed only to build the PDF)")
